/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal.app_tecnocomputer.Vista;

/**
 *
 * @author jaider carmona
 */
public class Vista_cliente extends javax.swing.JFrame {

      
      
    
    /**
     * Creates Vista_cliente
     */
    public Vista_cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        label_id = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        tex_name = new javax.swing.JTextField();
        tex_correo = new javax.swing.JTextField();
        tex_id = new javax.swing.JTextField();
        tex_user = new javax.swing.JTextField();
        label_correo = new javax.swing.JLabel();
        label_contrasena = new javax.swing.JLabel();
        boton_save = new javax.swing.JButton();
        boton_mod = new javax.swing.JButton();
        boton_dele = new javax.swing.JButton();
        boton_buscar = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();
        tex_contrasena = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(186, 192, 252));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(34, 46, 227)))); // NOI18N

        label_id.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        label_id.setText("ID:");

        label_name.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        label_name.setText("Nombre Completo:");

        label_user.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        label_user.setText("Usuario:");

        tex_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_nameActionPerformed(evt);
            }
        });

        tex_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_correoActionPerformed(evt);
            }
        });

        tex_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_idActionPerformed(evt);
            }
        });

        tex_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_userActionPerformed(evt);
            }
        });

        label_correo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        label_correo.setText("Correo Electronico:");

        label_contrasena.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        label_contrasena.setText("Contraseña:");

        boton_save.setBackground(new java.awt.Color(34, 46, 227));
        boton_save.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        boton_save.setForeground(new java.awt.Color(255, 255, 255));
        boton_save.setText("Guardar");
        boton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_saveActionPerformed(evt);
            }
        });

        boton_mod.setBackground(new java.awt.Color(34, 46, 227));
        boton_mod.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        boton_mod.setForeground(new java.awt.Color(255, 255, 255));
        boton_mod.setText("Modificar");
        boton_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modActionPerformed(evt);
            }
        });

        boton_dele.setBackground(new java.awt.Color(34, 46, 227));
        boton_dele.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        boton_dele.setForeground(new java.awt.Color(255, 255, 255));
        boton_dele.setText("Eliminar");
        boton_dele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_deleActionPerformed(evt);
            }
        });

        boton_buscar.setBackground(new java.awt.Color(34, 46, 227));
        boton_buscar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        boton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        boton_limpiar.setBackground(new java.awt.Color(79, 79, 231));
        boton_limpiar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        boton_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });

        tex_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_contrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_dele, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(boton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_id)
                    .addComponent(label_name)
                    .addComponent(label_user)
                    .addComponent(label_correo)
                    .addComponent(label_contrasena))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tex_id, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tex_correo)
                        .addComponent(tex_name, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tex_user, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tex_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tex_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tex_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_user)
                    .addComponent(tex_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_contrasena)
                    .addComponent(tex_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tex_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_correo))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_save)
                    .addComponent(boton_dele)
                    .addComponent(boton_limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_mod)
                    .addComponent(boton_buscar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tecnocomputer");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Registrarse!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tex_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tex_nameActionPerformed

    private void tex_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tex_correoActionPerformed

    private void tex_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_idActionPerformed
      
    }//GEN-LAST:event_tex_idActionPerformed

    private void tex_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tex_userActionPerformed

    private void boton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_saveActionPerformed

    }//GEN-LAST:event_boton_saveActionPerformed

    private void boton_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_modActionPerformed

    private void boton_deleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_deleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_deleActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed

    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_limpiarActionPerformed

    private void tex_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tex_contrasenaActionPerformed
    
   
    
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_cliente().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_buscar;
    public javax.swing.JButton boton_dele;
    public javax.swing.JButton boton_limpiar;
    public javax.swing.JButton boton_mod;
    public javax.swing.JButton boton_save;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_contrasena;
    private javax.swing.JLabel label_correo;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_user;
    public javax.swing.JPasswordField tex_contrasena;
    public javax.swing.JTextField tex_correo;
    public javax.swing.JTextField tex_id;
    public javax.swing.JTextField tex_name;
    public javax.swing.JTextField tex_user;
    // End of variables declaration//GEN-END:variables
}
